sudo: required
services:
- docker
script:
- sh build.sh
deploy:
  provider: s3
  access_key_id: AKIARALJXCFBKHO2JNEE
  bucket: sg-peppolgiude
  local-dir: target/site
  acl: public_read
  on:
    repo: SG-PEPPOL/SG-PEPPOL-Specifications
    branch: feature/PEPPOLSync
  skip_cleanup: 'true'
  secret_access_key:
    secure: R5G3pB9E9z6ljfkucw3jiuvOBxnoTeI6MMOnrI05OkF79SX5VyA+VvtUR5M3a2L9YkJIm0qd0ADPM0u9NgasQeXelTO27nk2W9wAGT0v7vYrszr1DFE3uXxgq9hzg7jpu2MtkLuBAkDZm92qpBkmuQfHNgfU1mdHrwrUWAgq+lYo2P0N6kbMMUsWiLMv+2uXm3DVyhW8rhTvMuoUzK6SJsJjNw+TVpSQsux5pgBkYkBqvkxxHZollpp/BNcCezaOHqa0RDKgVsprgbZMM1JfSLq+hV55h1QBdPahSjNypRlfKmifJzs+K0avxoCpogPQDy7Khyb8JaZRxpRav1ppxJM/DCcvRsST9qOYJiDzzH7HZitt6ljHC6vnnFTE0Q8eqRAlC9V0IJcLJCC9dfMof9Vchaqc2nWDqhbv9uD30sMoH9O+xXB6TSiwejsynF0jF6QLNj9Kh1KYebUjwsiZo20yAwV8iBMXL5ItiOlnKLVjxHx1bdUC2H6F9MEoucmlJZcbWi9cPWAJWuY+XL9gA336bEY1+nFso1vIe3eAzLt8gghr72tkaGdi+5qDChxy+THIgv5xqkK6SQEEBPuBCkg8CJZpI4SzHuvVV3I6o0OCUjomyFADKZjBSfhzxA7N7R8O2PUjqxsCyOvUxV/5rudVQhXMaIWbGdg2g+6WoUg=
