sudo: required
services:
- docker
script:
- sh build.sh
deploy:
  provider: s3
  access_key_id: AKIARALJXCFBKHO2JNEE
  secret_access_key:
    secure: QdOg2fAKDonRUWyLdeKF7R7emr9LGKJOzQsVWylfoYbWTXEUOk4qeN3Ieo+n39q3gVNOB6OHWME7haOlji2JXuqK/lylAyRYydE2WAskkKGAJzlv5ccy5TaKSGGEmk2QuLuE5unA/LdCNBbDKzOg0n1NRoKfDw9Yq7fQukw23JVx8iw90c3n03kS60FhuqnNn0NiBJVlyWfNuJQsfDFlAgGGi4ckp9XW7HXhZ0KG33j8bHDf+wkL2rDbB5Q9ZwGaX10zfzH2mIshe9nbO6GUdpTiZ8e/MPu4VPXxgWl8ehw/bUi1Blrq/vRLuQZc94HLj+K98gQb8o9wN686N6xPp8h+RzsIkqXyY5Tbazmc+uDJ5pAWLvF+sHcfDVqh0y8CJ+hnGx9B3yaoi+dwi8f/6rT/CPYEQ1pG9sPGcEKC19pV3+d6JEnf+xGEif4hcFv0wUPcpuHb17d3UDRRkIVyJXPCREVqE1medM3kd6oKHfEAfGI87llsUp1TcfcfzU++u9mao9GBGXy+jdno97m74a1lqWCP6SGFNE+b4ZluAHMdJPxopqYo6vvlWU5tSXX8v9ilc2tyc8Y6f8WcLaXHBppcn2IVrs4/ku4hX0n1P1dr9AxfvfnDWPMAdruPNPg3XI+xJovFeV1+2TYT2WxpFVZ5Jtdde8S0/aPOt+xrC5w=
  bucket: sg-peppolguide
  region: ap-southeast-1
  local-dir: target/site
  acl: public_read
  on:
    repo: SG-PEPPOL/SG-PEPPOL-Specifications
    branch: feature/PEPPOLSync
  skip_cleanup: 'true'
